spring:
  application:
    name: produto
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/produtos
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
